//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public int id { get; set; }
        public string scenario_id { get; set; }
        public Nullable<int> requirement_id { get; set; }
        public string scenario_description { get; set; }
        public Nullable<double> new_tcs_very_simple { get; set; }
        public Nullable<double> new_tcs_normal { get; set; }
        public Nullable<double> new_tcs_complex { get; set; }
        public Nullable<double> changed_tcs_very_simple { get; set; }
        public Nullable<double> changed_tcs_normal { get; set; }
        public Nullable<double> changed_tcs_complex { get; set; }
        public Nullable<double> nb_tc_short { get; set; }
        public Nullable<double> nb_tc_normal { get; set; }
        public Nullable<double> nb_tc_very_long { get; set; }
        public Nullable<double> new_tcs_effort_per_scenario { get; set; }
        public Nullable<double> chanegd_tcs_effort_per_scenario { get; set; }
    
        public virtual CR_Estimation CR_Estimation { get; set; }
    }
}
